name: Self-Hosted CI

on:
  pull_request:
    branches:
      - main
    paths:
    - bin/*

env:  
  DOTNET_VERSION: '6.0.422' 
  DOTNET_INSTALL_DIR: "./.dotnet"

jobs:
  Dotnet_Build:
    runs-on: self-hosted  
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4 
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
 
