name: CI

on:
  workflow_dispatch:
  push: 
    branches:
    - feature-private
jobs:
  cd_deployment:
   runs-on: self-hosted
   steps: 
    - name: AZ login
      run: az login --service-principal -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_PASSWORD }} --tenant ${{secrets.AZ_TENANT}}

    - uses: Azure/get-keyvault-secrets@v1
      with:
          keyvault: "Sharnikeyvault"
          secrets: 'LOGGING-DEFAULT, LOGGING-MICROSOFT, ALLOWED-HOSTS'
      id: DemoSecretAction
        
    - name: Replace tokens in appsettings.json
      uses: microsoft/replace-tokens@v2
      with:
        files: appsettings.json
