# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - sharnithawebapp

on:
#   push:
#     branches:
#       - feature-private
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://githubcisharni.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_c0e4b3adfe9c48fb84564470a04cb931 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1685a9fa6b16455fb7be3becdedae4bf }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: githubcisharni.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c0e4b3adfe9c48fb84564470a04cb931 }}/demoenv:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'sharnithawebapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_de55fd5575424801903b5377385c3eab }}
        images: 'githubcisharni.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c0e4b3adfe9c48fb84564470a04cb931 }}/demoenv:${{ github.sha }}'
