name: PR for Pages directory

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'Pages/**'
    branches:
      - develop
      
env:   
  DOTNET_VERSION: '6.0.422' 
  DOTNET_INSTALL_DIR: "./.dotnet" 

jobs:
  Frontend_Dotnet_Build:
    runs-on: self-hosted  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Begin SonarQube analysis
        run: |
          dotnet sonarscanner begin /k:"demoproject" \
          /d:sonar.login="admin" \
          /d:sonar.password="Admin@123" \
          /d:sonar.host.url="http://20.55.36.68:9000/" \
          /v:"${{ github.run_number }}" \
          /d:sonar.cs.vstest.reportsPaths="${{ github.workspace }}/*.trx" \
          /d:sonar.cs.vscoveragexml.reportsPaths="${{ github.workspace }}/TestResults/coverage.xml"
