name: PR for Pages directory

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'Pages/**'
    branches:
      - develop
      
env:   
  DOTNET_VERSION: '6.0.422' 
  DOTNET_INSTALL_DIR: "./.dotnet" 

jobs:
  Backend_Dotnet_Build:
    runs-on: self-hosted  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4 
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Checking Dotnet version
        run: dotnet --version
      - name: Install Dependency
        run: dotnet restore
      - name: Dotnet build
        run: dotnet build -c release
        
      - name: Verify Java version
        run: java --version
  
      - name: SonarScanner tool installed
        run: dotnet tool install --global dotnet-sonarscanner
        
      - name: Begin SonarQube analysis
        run: |
          dotnet sonarscanner begin /k:"demo1" \
          /d:sonar.login="admin" \
          /d:sonar.password="Sharni" \
          /d:sonar.host.url="http://74.235.205.8:9000/" \
          /v:"${{ github.run_number }}" \
        # /d:sonar.cs.vstest.reportsPaths="${{ github.workspace }}/*.trx" \
          # /d:sonar.cs.vscoveragexml.reportsPaths="${{ github.workspace }}/TestResults/coverage.xml"
  
      - name: Build project
        run: |
          dotnet build -c release -o app/publish
          cd app/publish && ls
          
      - name: End SonarQube analysis
        run: |
          dotnet sonarscanner end /d:sonar.login="admin" /d:sonar.password="Sharni"
