name: PR for Pages directory

on:
  pull_request:
    paths:
      - 'Pages/**'
      - 'output/**'
    branches:
      - develop
env:   
  DOTNET_VERSION: '6.0.422' 
  DOTNET_INSTALL_DIR: "./.dotnet" 

jobs:
  pr_Dotnet_Build:
    runs-on: self-hosted  
    steps:
      - name: lsi
        run: echo "Helloworld"

   
