name: Self-Hosted 

on:
  workflow_dispatch:
  push:
    # paths:
    #   - 'Pages/**'
      # Trigger only when changes are made in the Pages directory
    branches:
      - feature-private

jobs:
  Docker_Builds:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Docker build using Dockerfile
        run: |
          docker build -t githubcisharni.azurecr.io/demoenv:${{ github.run_id }} .
