name: Create Release Tag

on:
  push:
    branches:
      - demotestbranch
      
jobs:
  create-tag:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # - name: Get source branch
      #   id: branch
      #   run: |
      #     MSG=$(git log -1 --pretty=%B)
      
      #     echo "Commit Message:"
      #     echo "$MSG"
      
      #     BRANCH=$(echo "$MSG" | head -n1 | sed -n 's|.*from .*/|p')
      
      #     echo "Branch: $BRANCH"
      
      #     echo "source_branch=$BRANCH" >> $GITHUB_OUTPUT

      # - name: Extract Version
      #   id: version
      #   run: |
      #     BRANCH="${{ steps.branch.outputs.source_branch }}"
      
      #     if [[ "$BRANCH" =~ ^release/ ]]; then
      #       VERSION="${BRANCH#release/}"
      
      #       echo "version=$VERSION" >> $GITHUB_OUTPUT
      
      #       echo "Version: $VERSION"
      #     else
      #       echo "Not a release branch: $BRANCH"
      #       exit 1
      #     fi

      - name: Get Release Version
        id: version
        run: |
          MSG=$(git log -1 --pretty=%B)
      
          VERSION=$(echo "$MSG" | grep -oE 'release/[0-9]+\.[0-9]+\.[0-9]+' | cut -d'/' -f2)
          echo "version number: $VERSION"
          
          if [ -z "$VERSION" ]; then
            echo "Unable to determine release version"
            exit 1
          fi
      
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          
      - name: Check If Tag Exists
        id: tag_check
        run: |
          TAG="v${{ steps.version.outputs.version }}"

          if git ls-remote --tags origin "$TAG" | grep -q "$TAG"; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Git Tag
        if: steps.tag_check.outputs.exists == 'false'
        run: |
          TAG="v${{ steps.version.outputs.version }}"

          git config user.name "Sharnitha"
          git config user.email "sharnitha@github.com"

          git tag "$TAG"
          git push origin "$TAG"
          
      - name: Create Git Tag
        if: steps.tag_check.outputs.exists == 'true'
        run: |
          echo "Already tag is available"
          
      - name: Display Tag
        run: |
          echo "Created tag: v${{ steps.version.outputs.version }}"
