name: Self-Hosted CI

on:
  push:
    branches:
    - feature-private

env: 
  DOTNET_VERSION: '6.0.422'
  DOTNET_INSTALL_DIR: "./.dotnet"

jobs:
  Dotnet_Build:
    runs-on: self-hosted  
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ secrets.DOTNET_VERSION }}
  
    - name: Checking Dotnet version
      run: dotnet --version
    - name: Install Dependency
      run: dotnet restore
    - name: Dotnet build
      run: dotnet build -c release
    - name: Dotnet publish
      run: dotnet publish -c release
           
    #    - name: Begin SonarQube analysis
    #   run: |
    #     dotnet sonarscanner begin /k:"demoprij" \
    #     /d:sonar.login="admin" \
    #     /d:sonar.password="Sonar@123" \
    #     /d:sonar.host.url="http://172.212.80.62:9000/" \
    #     /v:"${{ github.run_number }}" \
    #     /d:sonar.cs.vstest.reportsPaths="${{ github.workspace }}/*.trx" \
    #     /d:sonar.cs.vscoveragexml.reportsPaths="${{ github.workspace }}/TestResults/coverage.xml"
    # - name: Build project
    #   run: |
    #     dotnet build -c release -o app/publish
    #     cd app/publish && ls
        
    # - name: End SonarQube analysis
    #   run: |
    #     dotnet sonarscanner end /d:sonar.login="admin" /d:sonar.password="Sonar@123"
