name: CD on GitHub
on:
#   push:
#     branches:
#       - feature-private 
      
  workflow_run:
    workflows: 
      - Self-Hosted CI
    types:
      - completed
jobs:
    update-deployment:
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      environment:
        name: Dev
      runs-on: self-hosted
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: list
          run:
            ls

        - name: download artifacts
          run: |
            gh run download ${{ github.event.workflow_run.id }} -n publish -D /opt/actions-runner/_work/newrepo-dotnet/newrepo-dotnet/
           
     # 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
        # - name: Download build artifacts
        #   uses: actions/download-artifact@v2
        #   with:
        #     name: publish
        #     package: '/opt/actions-runner/_work/newrepo-dotnet/newrepo-dotnet/*'
            
        - name: Deploy Docker image
          run: |
            az login --service-principal -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_PASSWORD }} --tenant ${{secrets.DOCKER_TENANT}}
        # az webapp config appsettings set --name sharnithawebapp --resource-group sharnitha-poc --settings __DEFAULT__="Information"

        - name: Deploy Docker image
          run: |
            LOG_DEFAULT = ${{ secrets.DEFAULTGITHUB }}
            echo "Retrieved log level default: $LOG_DEFAULT"
            sed -i "s|__DEFAULT__|$LOG_DEFAULT|g" /app/appsettings.json

        # LOG_DEFAULT=$(az keyvault secret show --name logLevel-default --vault-name keyvault110624 --query value -o tsv)


        - name: Deploy to Azure Web App
          uses: azure/webapps-deploy@v2
          with:
              app-name: 'webappcontainer23'
              slot-name: 'production'
              publish-profile: ${{ secrets.AZUREWEBAPPPUBLISHPROFILE }}
              package: '/opt/actions-runner/_work/newrepo-dotnet/newrepo-dotnet/*'
            

        
        # - uses: azure/appservice-settings@v1
        #   with:
        #     app-name: 'sharnithawebapp'
        #     mask-inputs: true
        #     slot-name: 'production'  # Optional and needed only if the settings have to be configured on the specific deployment slot
        #     app-settings-json: '[{ "name": "__DEFAULT__", "value": "Information", "__MICROSOFT__": "Warning" }]'
     

        # - uses: azure/webapps-deploy@v2
        #   with: 
        #     app-name: 'webappcontainer23'
        #     slot-name: 'production'
        #     publish-profile: ${{ secrets.AZUREWEBAPPPUBLISHPROFILE }}
        #     images: 'githubcisharni.azurecr.io/demoenv:${{ github.event.workflow_run.id }}'
      

# name: cd on GitHub
# on:
#   workflow_run:
#     workflows: 
#       - Self-Hosted CI
#     types:
#       - completed
# jobs:
#     update-deployment:
#       if: ${{ github.event.workflow_run.conclusion == 'success' }}
#       environment:
#         name: Dev
#       runs-on: self-hosted
#       steps:
        
#         # - name: az cli
#         #   run: az login --service-principal -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_PASSWORD }} --tenant ${{ secrets.DOCKER_TENANT }}
  
#         # - name: Azure CLI script
#         #   id: step_one
#         #   uses: azure/CLI@v1
#         #   with:
#         #     inlineScript: |
#         #       echo secret=$(az keyvault secret show --vault-name Pracvault123 --name MySecret --query value) >> $GITHUB_ENV
              
#         # - name: Use the value
#         #   id: step_two
#         #   run: |
#         #       echo "${{ env.secret }}"

#       # - uses: cschleiden/replace-tokens@v1
#       #   with:
#       #     tokenPrefix: '{'
#       #     tokenSuffix: '}'
#       #     files: 'appsettings.json'
              
#       # - name: Azure WebApp
#       #   uses: Azure/webapps-deploy@v3.0.1
#       #   with:
#       #       app-name: Sharni 
#       #       images: githubcipractice.azurecr.io/demoenv:${{ github.run_id }}
