name: TestingBranch-CD
on:      
  workflow_run:   
    workflows: 
      - TestingBranch
    types:
      - completed
jobs:
    Dev-deployment:
      if: ${{ github.event.workflow_run.conclusion == 'success'  && github.ref == 'refs/heads/branchswitch' }}
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2  
        - name: echo 
          run: Hi

    Prod-deployment:
      if: ${{ github.event.workflow_run.conclusion == 'success'  && github.ref == 'refs/heads/Perf' }}
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2  
        - name: echo 
          run: Hello
   
#         #   with:
#         #     inlineScript: |
#         #       echo secret=$(az keyvault secret show --vault-name Pracvault123 --name MySecret --query value) >> $GITHUB_ENV
              
#         # - name: Use the value
#         #   id: step_two
#         #   run: |
#         #       echo "${{ env.secret }}"

#       # - uses: cschleiden/replace-tokens@v1
#       #   with:
#       #     tokenPrefix: '{'
#       #     tokenSuffix: '}'
#       #     files: 'appsettings.json'
              
#       # - name: Azure WebApp
#       #   uses: Azure/webapps-deploy@v3.0.1
#       #   with:
#       #       app-name: Sharni 
#       #       images: githubcipractice.azurecr.io/demoenv:${{ github.run_id }}
