name: Frontend-CI

on:
  workflow_dispatch:
  push:
    branches:  
      - feature/test 
       
jobs:   
  set_environment:   
    runs-on: test
    # needs: demo 
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Determine environment based on branch
        id: set_env
        run: |
          echo "Hello"
