name: Select and Deploy Release
on:
  workflow_dispatch:
    inputs:
      release_tag:
        type: string
        description: 'The tag of the release to use (e.g., v1.0.1)'
        required: true
        default: 'latest'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      # - name: Use the selected release tag
      #   run: |
      #     echo "Deploying release: ${{ inputs.release_tag }}

      - name: Determine Release Tag
        id: vars
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if [ "${{ github.event.inputs.release_tag }}" == "latest" ]; then
            # Get the tag name of the latest release
            TAG=$(gh release view --json tagName --template '{{.tagName}}')
          else
            TAG="${{ github.event.inputs.release_tag }}"
          fi
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "Selected Tag: $TAG"

      - name: Download Release Asset
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Downloads the build artifact (e.g., build.zip) from the specific release
          gh release download ${{ steps.vars.outputs.tag }} --pattern '*releasetest.zip' --dir ./deployment-artfiact

      - name: Deploy to Prod Azure Web App
        if: github.ref_name == 'test-zip'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'testzipdeploy01'
          publish-profile: ${{ secrets.ZIP_APPSERVICE_PUBLISH_TOKEN }}
          package: ./releasetest.zip
